theme: jekyll-theme-slate  
title: My amazing post
showGitHubRibbon: true
{% if site.showGitHubRibbon %}
  <li>
    <a href="https://twitter.com">
      <i class="fa fa-twitter"></i> Twitter
    </a>
  </li>
{% endif %}
