remote_theme: emrickj/themes2
title: My amazing post
show_downloads: true
preview_path: https://www.gem-editor.com/gwc/theme
collections:
  webpages:
    output: true
defaults:
  - scope:
      path: ""
      type: webpages
    values:
      layout: page
